FROM golang:1.26.0-alpine

RUN apk add --no-cache git netcat-openbsd

WORKDIR /app

RUN go install github.com/cespare/reflex@latest

RUN go install github.com/go-delve/delve/cmd/dlv@latest

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 8080 2345

CMD ["sh", "-c", "reflex -r '\\.go$' -s -- go run ./cmd/conduit/main.go -c config.container.yaml"]
