DROP TABLE IF EXISTS certificate_download_tokens CASCADE;
DROP TABLE IF EXISTS issued_certificates CASCADE;
DROP TABLE IF EXISTS certificate_events CASCADE;
DROP TABLE IF EXISTS certificate_downloads CASCADE;
DROP TABLE IF EXISTS certificate_requests CASCADE;
DROP TABLE IF EXISTS service_account_scopes CASCADE;
DROP TABLE IF EXISTS service_accounts CASCADE;
DROP TABLE IF EXISTS user_groups CASCADE;
DROP TABLE IF EXISTS users CASCADE;